name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  # Needed in order to leave comments on pull requests.
  pull-requests: 'write'

jobs:
  check-depgraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Install cargo-depgraph
        run: cargo install cargo-depgraph

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Generate new depgraph
        run: cargo depgraph --workspace-only | tred | dot -Tsvg -o depgraph.svg

      - name: Check depgraph for changes
        run: git diff --exit-code depgraph.svg

      - name: Leave Comment
        uses: thollander/actions-comment-pull-request@v2
        if: steps.check_for_diff.conclusion == 'failure'
        with:
          message: |
            Depgraph changed!
          comment_tag: depgraph
          mode: recreate
