name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  # Needed in order to leave comments on pull requests.
  pull-requests: 'write'

jobs:
  check-depgraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Install cargo-depgraph
        uses: baptiste0928/cargo-install@v2.1.0
        with:
          crate: cargo-depgraph

      - name: Install graphviz
        run: sudo apt update && sudo apt install -y graphviz

      - name: Generate new depgraph
        run: cargo depgraph --workspace-only | tred | dot -Tsvg -o depgraph.svg

      - name: Check depgraph diff
        run: git diff --exit-code depgraph.svg > depgraph.patch

      - name: Create comment file
        if: ${{ failure() }}
        run: |
          echo "It looks like this pull request changed the workspace dependency graph. \
          Please replace \`assets/depgraph.svg\` with the following text:
          
          <details>
            <summary>depgraph.svg</summary>
            
            \`\`\`html" >> pr-comment.txt
          cat depgraph.svg >> pr-comment.txt
          echo "  \`\`\`
          </details>
          
          <details>
            <summary>Diff against previous</summary>

            \`\`\`patch" >> pr-comment.txt
          echo "  $(cat depgraph.patch)
            \`\`\`
          </details>" >> pr-comment.txt

      # - name: Leave comment
      #   if: ${{ failure() }}
      #   uses: thollander/actions-comment-pull-request@v2
      #   with:
      #     filePath: pr-comment.txt
      #     comment_tag: depgraph
      #     mode: recreate

      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ failure() }}
        with:
          recreate: true
          header: depgraph
          path: pr-comment.txt
