name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  # Needed in order to leave comments on pull requests.
  pull-requests: 'write'

jobs:
  check-depgraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Install cargo-depgraph
        uses: baptiste0928/cargo-install@v2.1.0
        with:
          crate: cargo-depgraph

      - name: Install Graphviz
        run: sudo apt update && sudo apt install -y graphviz

      - name: Generate new depgraph
        run: cargo depgraph --workspace-only | tred | dot -Tsvg -o depgraph.svg

      - name: Check depgraph for changes
        run: git diff --exit-code depgraph.svg

      - name: Create comment file
        if: ${{ failure() }}
        run: |
          echo "Looks like the workspace dependency graph was changed.
          Please place the following text in \`assets/depgraph.svg\`
          
          <details>
            <summary>depgraph.svg</summary>
          ```html
          $(cat depgraph.svg)
          ```
          </details>" >> pr-comment.txt

      - name: Leave Comment
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr-comment.txt
          comment_tag: depgraph
          mode: recreate
