name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  # Needed in order to leave comments on pull requests.
  pull-requests: 'write'

jobs:
  check-depgraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cargo install cargo-depgraph
          sudo apt-get update && sudo apt-get install -y graphviz

      - name: Hello world
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello World!
          comment_tag: depgraph
          mode: recreate
